### ISSUE TITLE
MongoDB Request PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by gokcenveysel** [chartbrew/chartbrew#114]
Hi @razvanilin,

When I create mongodb connection and create data for any chart I got "PayloadTooLargeError" from backend server.

```
PayloadTooLargeError: request entity too large
    at readStream (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/raw-body/index.js:156:17)
    at getRawBody (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/raw-body/index.js:109:12)
    at read (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/body-parser/lib/read.js:79:3)
    at jsonParser (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/body-parser/lib/types/json.js:135:5)
    at Layer.handle [as handle_request] (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:328:13)
    at /home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:346:12)
    at next (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:280:10)
    at urlencodedParser (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/body-parser/lib/types/urlencoded.js:100:7)
    at Layer.handle [as handle_request] (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:328:13)
    at /home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:346:12)
    at next (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:280:10)
    at cookieParser (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/cookie-parser/index.js:57:14)
    at Layer.handle [as handle_request] (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:328:13)
    at /home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:346:12)
    at next (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:280:10)
    at /home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/connect-busboy/index.js:14:14
    at Layer.handle [as handle_request] (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:328:13)
    at /home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:346:12)
    at next (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:280:10)
    at expressInit (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/middleware/init.js:40:5)
Cannot read property 'indexOf' of null
PayloadTooLargeError: request entity too large
    at readStream (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/raw-body/index.js:156:17)
    at getRawBody (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/raw-body/index.js:109:12)
    at read (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/body-parser/lib/read.js:79:3)
    at jsonParser (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/body-parser/lib/types/json.js:135:5)
    at Layer.handle [as handle_request] (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:328:13)
    at /home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:346:12)
    at next (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:280:10)
    at urlencodedParser (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/body-parser/lib/types/urlencoded.js:100:7)
    at Layer.handle [as handle_request] (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:328:13)
    at /home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:346:12)
    at next (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:280:10)
    at cookieParser (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/cookie-parser/index.js:57:14)
    at Layer.handle [as handle_request] (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:328:13)
    at /home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:346:12)
    at next (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:280:10)
    at /home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/connect-busboy/index.js:14:14
    at Layer.handle [as handle_request] (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:328:13)
    at /home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:346:12)
    at next (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/router/index.js:280:10)
    at expressInit (/home/qa-chart-brew/chartbrew/chartbrew/server/node_modules/express/lib/middleware/init.js:40:5)
```

Is there any solution for that problem?

**Comment by razvanilin** [comment]
Hey @gokcenveysel ,

I haven't seen that error on my end yet, but it looks like the data being sent to the server is above the limits allowed by Express. Can you try modifying `server/index.js` and see if it fixes the issue?

Replace lines [38 and 39](https://github.com/chartbrew/chartbrew/blob/c18451d81eb40d838c186623d35195927f722d2e/server/index.js#L38) with the lines below:

```
app.use(urlencoded({ limit: "2mb", extended: true }));
app.use(json({ limit: "2mb" });
```

if you still get the error, try adding a bigger value instead of the `2mb` in the example.

**Comment by gokcenveysel** [comment]
Hey @razvanilin,

Your suggested solution worked for me!

Thanks.
