### ISSUE TITLE
Windows Dev - error: 400 - "Missing required arguments to create the template

### ISSUE THREAD

**Issue by scottdevopsgithub** [chartbrew/chartbrew#122]
This seems to be the error message I am getting: StatusCodeError: 400 - "Missing required arguments to create the template" when trying to create new charts on a new or (using an)existing dashboard.

I installed the strapi plugin, into my working strapi backend project. The plugin seems to be up and running as expected, as far as I can tell. I configured all of it, as you explained in your recent youtube video, and based on information I see in the readme file(s).

So once all that was up and running, I tried to create a set of charts for my strapi users, and it is not working. I get the error messages you see in the attached text file.  Also, I attached a screenshot of my working strapi chartbrew plugin.
[missing requireed arguments when creating new charts.txt](https://github.com/chartbrew/chartbrew/files/9041243/missing.requireed.arguments.when.creating.new.charts.txt)

![Error Creating Strapi User Charts](https://user-images.githubusercontent.com/96550228/177196868-1200e566-75cb-47ea-a5f4-f71af289aa6e.png)

Here is the error

[2022-07-04 12:02:43.557] http: GET /chartbrew/settings (33 ms) 200
[2022-07-04 12:02:44.257] error: 400 - "Missing required arguments to create the template"
StatusCodeError: 400 - "Missing required arguments to create the template"
    at new StatusCodeError (C:\code\backend\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\code\backend\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\code\backend\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\code\backend\node_modules\request\request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.emit (node:domain:475:12)
    at Request.<anonymous> (C:\code\backend\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:527:28)
    at Request.emit (node:domain:475:12)
    at IncomingMessage.<anonymous> (C:\code\backend\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:539:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
From previous event:
    at Request.plumbing.init (C:\code\backend\node_modules\request-promise-core\lib\plumbing.js:36:28)
    at Request.RP$initInterceptor [as init] (C:\code\backend\node_modules\request-promise-core\configure\request2.js:41:27)
    at new Request (C:\code\backend\node_modules\request\request.js:127:8)
    at request (C:\code\backend\node_modules\request\index.js:53:10)
    at Object.generate (C:\code\backend\node_modules\@chartbrew\plugin-strapi\server\services\chartbrew.js:111:11)
    at async Object.generateTemplate (C:\code\backend\node_modules\@chartbrew\plugin-strapi\server\controllers\chartbrew.js:64:23)
    at async returnBodyMiddleware (C:\code\backend\node_modules\@strapi\strapi\lib\services\server\compose-endpoint.js:52:18)
    at async policiesMiddleware (C:\code\backend\node_modules\@strapi\strapi\lib\services\server\policy.js:24:5)
    at async C:\code\backend\node_modules\@strapi\strapi\lib\middlewares\body.js:51:9
    at async C:\code\backend\node_modules\@strapi\strapi\lib\middlewares\logger.js:22:5
    at async C:\code\backend\node_modules\@strapi\strapi\lib\middlewares\powered-by.js:16:5
    at async cors (C:\code\backend\node_modules\@koa\cors\index.js:95:16)
    at async C:\code\backend\node_modules\@strapi\strapi\lib\middlewares\errors.js:13:7
    at async session (C:\code\backend\node_modules\koa-session\index.js:41:7)
    at async C:\code\backend\node_modules\@strapi\strapi\lib\services\metrics\middleware.js:29:5

**Comment by razvanilin** [comment]
Hey @scottdevopsgithub have you added the Strapi API token in the plugin settings? See below:
![image](https://user-images.githubusercontent.com/5342321/177200035-384e89e5-7ab1-4bf1-9b11-27d1ccee8731.png)

**Comment by scottdevopsgithub** [comment]
So, yep, I went into my Strapi Admin panel, and viewed the Settings page, and there I created a Read Only API token, and pasted that token into the location you showed in your screenshot (and hit save button of course).  :-)

I also went into the chartbrew admin panel, and deleted those user reports you see in my first screenshot. And then after hitting refresh in my strapi admin panel...they disappeared from the drop down list in the Chartbrew plug in screens (in the screenshot below here). 

So I know that my strapi admin panel is communicating (partially anyway) with my self-hosted Chartbrew server that is running locally.  

![image](https://user-images.githubusercontent.com/96550228/177225871-0eb1f463-a51e-47c7-89b8-aa649a0147d3.png)

**Comment by razvanilin** [comment]
Oh, something I realized now. Are you running Strapi on your local machine? If yes, then the Heroku app cannot access your Strapi instance

**Comment by scottdevopsgithub** [comment]
Let me do a quick review, which I think will answer your question.  There is a lot going on here so....let me break it down:
1. I have the self hosted chartbrew (server side code) running on heroku
2. I have mysql for chartbrew also running in heroku for chartbrew
3. I have the env vars on heroku, pointed at the heroku version of the mysql database
4. My strapi backend is also hosted on heroku, and has been up and running fine
5. I have hosted the frontend chartbrew on vercel, and it is now up and running (based on our other github Issue that was resolved).  And I have created some charts on this vercel chartbrew instance (which is pointed at the heroku chartbrew instance/mysql)

6. However,  I have not yet pushed my localhost version of my strapi backend out to heroku. This is the version I have been messing with, and is the version that has the chartbrew plugin running in the strapi admin panel.

7. In my localhost version of my strapi backend/admin panel, the chartbrew plugin is pointed at the heroku version of chartbrew (both for frontend and backend). 
8. I have also created the API tokens needed by the chartbrew strapi plugin

9. I created some charts while logged in and using the vercel chartbrew instance of the application...and I can see those chartbrew charts in my localhost strapi chartbrew plugin. It is just when I try to create new charts from the strapi chartbrew plugin (while on my localhost version), is the only thing that is not working?

So far, everything else seems to be working now with the self-hosted chartbrew instances and the chartbrew plugin, except being able to create charts from my localhost version of the strapi admin panel (that is pointed at the hosted versions of the chartbrew frontend on vercel and chartbrew backend on heroku.

**Comment by scottdevopsgithub** [comment]
PS I have a question for clarification...when you mentioned that the 'heroku app' cannot access my strapi instance. 
1. Would the 'heroku app' you are referring to be my self-hosted chartbrew application that I have running on heroku?

**Comment by scottdevopsgithub** [comment]
OK, maybe something is still going wrong? I got the code deployed to heroku, and it is working better, but still now seeing a different kind of error. I setup all the API keys correctly and then attempted to create a new visualization in the chartbrew plugin, inside my (heroku) hosted strapi deployment.

Below is the error I am seeing happening. Just thought I would pass this along.   

PS The reason there are charts in my Chartbrew plugin screen in my strapi admin panel (that you see in the screenshot) is because I manually connected to the strapi instance from my chartbrew dashboard panel. So the Chartbrew admin panel hosted in vercel allows me to create charts for my strapi data (that you can see showing up in the chartbrew plugin in the screenshot below)

![error 2 when creating new chart using the plugin](https://user-images.githubusercontent.com/96550228/177685554-240cf102-027e-421b-bbf2-432d7d973bb6.png)

And here is my chartbrew admin panel, where you can see the three charts I created in there using the tools found in the chartbrew admin panel. From the chartbrew self-hosted instance, I pointed several API connections to my strapi API instance. So that is how it is working

![error  3 when creating new chart using the plugin](https://user-images.githubusercontent.com/96550228/177685656-2f3ca1a1-a72a-4f99-a381-c47a05a10674.png)

But when I try to create new chart visualizations from the Chartbrew plugin, (and then hit save while in the strapi admin panel) I am getting this error:

![error when creating new chart using the plugin](https://user-images.githubusercontent.com/96550228/177685825-25ef7d31-b69f-41b6-a63d-d867ff5e1dbc.png)

I am not sure why this is happening yet. Most of the chartbrew plugin does seem to be working. 

Do I need to change any Permissions in the strapi admin panel for Chartbrew?
