### ISSUE TITLE
Docker - latest & latest-arm64 failing

### ISSUE THREAD

**Issue by wesdobry** [chartbrew/chartbrew#127]
```
npx: installed 84 in 14.994s                                                                                      │
file:///root/.npm/_npx/315/lib/node_modules/serve/build/main.js:129                                               │
      url.port = url.port ?? "3000";                                                                              │
                           ^                                                                                      │
                                                                                                                  │
SyntaxError: Unexpected token '?'                                                                                 │
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)                                         │
    at async link (internal/modules/esm/module_job.js:42:21) 
```
The above error is presented when deploying the latest & latest-arm64 docker images.

Log:
```
Building the UI. This might take a couple of minutes...


> client@1.23.0 build /code/client
> npm run setup && cross-env REACT_APP_VERSION=$npm_package_version node scripts/build.js


> client@1.23.0 setup /code/client
> echo n | cp -vipr src/config/settings.template.js src/config/settings.js | true

Running server on port 4019
Creating an optimized production build...
cp: overwrite 'src/config/settings.js'? Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Error while cleaning the chart caches. You might want to delete them manually
Updated database schema to the latest version!
Compiled successfully.

File sizes after gzip:

  376.14 KB  build/static/js/6.4e45152d.chunk.js
<snip>
  112 B      build/fc47afbc1973c25ac5c07d588d993d6b.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  https://cra.link/deployment

npx: installed 84 in 14.169s
file:///root/.npm/_npx/88/lib/node_modules/serve/build/main.js:129
      url.port = url.port ?? "3000";
                           ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

Using this .env file mounted to /code/.env:

``` #### PRODUCTION VARS ####

    ### Database connection parameters
    CB_DB_NAME=chartbrew
    CB_DB_USERNAME=chartbrew
    CB_DB_PASSWORD=password
    CB_DB_HOST=chartbrew-db
    CB_DB_PORT=3306

    # set to 'mysql' or 'postgres'
    CB_DB_DIALECT=mysql

    ### A secret string which will be used to encrypt your data
    CB_SECRET=secret

    ### The API host string used on the server app
    CB_API_HOST=localhost
    CB_API_PORT=4019

    ### Used in the client app

    # The address where the front-end app sits
    REACT_APP_CLIENT_HOST=http://localhost:4018

    # The address where the backend API sits
    REACT_APP_API_HOST=http://localhost:4019

    # Email connection parameters for sending team signup invites and forgot password emails
    CB_MAIL_HOST=relay.server.com
    CB_MAIL_USER=
    CB_MAIL_PASS=
    # The admin email from which all the emails are delivered
    CB_ADMIN_MAIL=email@email.com

    # Restrict users from having their own team
    # 0 - users will have their own team
    # 1 - users can only be part of teams they are invited to
    CB_RESTRICT_TEAMS=0

    # Google cloud client ID information (To enable Google integrations)
    CB_GOOGLE_CLIENT_ID=
    CB_GOOGLE_CLIENT_SECRET=
```

DB is another container running mysql  named 'chartbrew-db' with a database 'chartbrew' and db user of 'chartbrew'.

I'm not a strong nodejs person.  I've been digging through the code, but I can't ascertain where this might be coming from based on the error information, or if this is even an issue with chartbrew vs a dependency.

**Comment by wesdobry** [comment]
Was able to replicate this on a standard install on Ubuntu, as well.

```Need to install the following packages:
  serve
Ok to proceed? (y) y
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'serve@14.0.0',
npm WARN EBADENGINE   required: { node: '>= 14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'boxen@7.0.0',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'camelcase@7.0.0',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
file:///home/wesdobry/.npm/_npx/aab42732f01924e5/node_modules/serve/build/main.js:129
      url.port = url.port ?? "3000";
                           ^

SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

**Comment by wesdobry** [comment]
Moving to node v14.20 appears to have corrected the issue on the standalone server.

**Comment by razvanilin** [comment]
Thanks for reporting this @wesdobry !

I just had a look and it seems the latest version of [`serve`](https://github.com/vercel/serve/releases/tag/14.0.0) is not supporting NodeJS 12 anymore and the docker image is installing the latest version to run the client application.

Moving to NodeJS v14 is indeed the solution for this. I'll take a look over your PR
