### ISSUE TITLE
Postgres Certificate Support

### ISSUE THREAD

**Issue by theaccordance** [chartbrew/chartbrew#129]
## User Story
As a resource owner, I want to implement Chartbrew using a Postgres Database that requires SSL 

## Details
The tech stack for my SaaS sandbox (`mainwaring.dev`) includes a managed Postgres DB cluster which is hosted on Digital Ocean.  DO requires SSL to connect to the database cluster.  I attempted to implement an self-hosted instance of Chartbrew using my existing DB cluster, but receive the following error in my terminal console:
```
ConnectionError [SequelizeConnectionError]: no pg_hba.conf entry for host "<<redacted>>", user "<<redacted>>", database "chartbrew", no encryption
    at Client._connectionCallback (/Users/mainwaring/projects/chartbrew/server/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:142:24)
    at Client._handleErrorWhileConnecting (/Users/mainwaring/projects/chartbrew/server/node_modules/pg/lib/client.js:305:19)
    at Client._handleErrorMessage (/Users/mainwaring/projects/chartbrew/server/node_modules/pg/lib/client.js:325:19)
    at Connection.emit (node:events:527:28)
    at /Users/mainwaring/projects/chartbrew/server/node_modules/pg/lib/connection.js:114:12
    at Parser.parse (/Users/mainwaring/projects/chartbrew/server/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/Users/mainwaring/projects/chartbrew/server/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
``` 

Before concluding that it was related to the SSL requirement, I performed the following troubleshooting steps:
* Verified the credentials for host, port, username, password, and database were correct
* Verified that the db cluster was still accessible to my other deployed applications 
* Verified that there were no connection issues between my local machine and the db cluster 

## Acceptance Criteria
* Expose an environment variable to specify a SSL Cert for Postgres
* Preferably, passing the contents of the cert as a string to the environment variable would be preferable as it makes it easier to store the cert in the same fashion as secrets, but a file reference is also satisfactory.

**Comment by razvanilin** [comment]
The DB configuration doesn't currently allow SSL certificates and these can be added here: https://github.com/chartbrew/chartbrew/blob/master/server/models/models/index.js#L28

Some more details from Sequelize docs: https://sequelize.org/docs/v6/other-topics/dialect-specific-things/#postgresql
