### ISSUE TITLE
!connections[connection.id]?.createNew: Unexpected token '.' in backend

### ISSUE THREAD

**Issue by AKumariGB** [chartbrew/chartbrew#174]
Hello,

I try to run chartbrew. The frontend works but the backend outputs the following error:

```
> server@v2.6.0 start-dev
> set NODE_ENV=development && nodemon index

[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index index.js`
/home/astha/Documents/github/chartbrew/server/templates/custom/builder.js:36
      && !connections[connection.id]?.createNew
                                     ^

SyntaxError: Unexpected token '.'
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/astha/Documents/github/chartbrew/server/templates/custom/model.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/astha/Documents/github/chartbrew/server/templates/index.js:10:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
[nodemon] app crashed - waiting for file changes before starting...
```
I've setup a local PostgreSQL DB and configured it in the .env file in the production and dev sections.

**Comment by AKumariGB** [comment]
@razvanilin yes indeed, and the problem was solved after updating it to a newer version. So thankyou :+1:  :)
