### ISSUE TITLE
SequelizeDatabaseError relation "ChartDatasetConfig" does not exist

### ISSUE THREAD

**Issue by odetolakehinde** [chartbrew/chartbrew#210]
When I try to initialize my application, I get this error. What could be wrong?

<img width="1354" alt="image" src="https://github.com/chartbrew/chartbrew/assets/26208992/68ec1d2f-de72-4b91-bb06-627db7669baa">

**Comment by odetolakehinde** [comment]
```
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index index.js`
(node:25452) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Running server on port 4019
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error
    at Query.run (/Users/ninja/Documents/coding/sendlovebox/chartbrew-be/server/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at /Users/ninja/Documents/coding/sendlovebox/chartbrew-be/server/node_modules/sequelize/lib/sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresQueryInterface.select (/Users/ninja/Documents/coding/sendlovebox/chartbrew-be/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async Chart.findAll (/Users/ninja/Documents/coding/sendlovebox/chartbrew-be/server/node_modules/sequelize/lib/model.js:1140:21) {
  name: 'SequelizeDatabaseError',
  parent: error: relation "ChartDatasetConfig" does not exist
      at Parser.parseErrorMessage (/Users/ninja/Documents/coding/sendlovebox/chartbrew-be/server/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/ninja/Documents/coding/sendlovebox/chartbrew-be/server/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/ninja/Documents/coding/sendlovebox/chartbrew-be/server/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/ninja/Documents/coding/sendlovebox/chartbrew-be/server/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:519:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 119,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '1394',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '1384',
    routine: 'parserOpenTable',
    sql: 'SELECT "Chart"."id", "Chart"."project_id", "Chart"."name", "Chart"."lastAutoUpdate", "Chart"."autoUpdate", "Chart"."chartData", "ChartDatasetConfigs"."id" AS "ChartDatasetConfigs.id", "ChartDatasetConfigs"."chart_id" AS "ChartDatasetConfigs.chart_id", "ChartDatasetConfigs"."dataset_id" AS "ChartDatasetConfigs.dataset_id", "ChartDatasetConfigs"."formula" AS "ChartDatasetConfigs.formula", "ChartDatasetConfigs"."datasetColor" AS "ChartDatasetConfigs.datasetColor", "ChartDatasetConfigs"."fillColor" AS "ChartDatasetConfigs.fillColor", "ChartDatasetConfigs"."fill" AS "ChartDatasetConfigs.fill", "ChartDatasetConfigs"."multiFill" AS "ChartDatasetConfigs.multiFill", "ChartDatasetConfigs"."legend" AS "ChartDatasetConfigs.legend", "ChartDatasetConfigs"."pointRadius" AS "ChartDatasetConfigs.pointRadius", "ChartDatasetConfigs"."excludedFields" AS "ChartDatasetConfigs.excludedFields", "ChartDatasetConfigs"."sort" AS "ChartDatasetConfigs.sort", "ChartDatasetConfigs"."columnsOrder" AS "ChartDatasetConfigs.columnsOrder", "ChartDatasetConfigs"."order" AS "ChartDatasetConfigs.order", "ChartDatasetConfigs"."maxRecords" AS "ChartDatasetConfigs.maxRecords", "ChartDatasetConfigs"."goal" AS "ChartDatasetConfigs.goal", "ChartDatasetConfigs"."createdAt" AS "ChartDatasetConfigs.createdAt", "ChartDatasetConfigs"."updatedAt" AS "ChartDatasetConfigs.updatedAt" FROM "Chart" AS "Chart" LEFT OUTER JOIN "ChartDatasetConfig" AS "ChartDatasetConfigs" ON "Chart"."id" = "ChartDatasetConfigs"."chart_id" WHERE "Chart"."autoUpdate" > 0;',
    parameters: undefined
```

**Comment by razvanilin** [comment]
Hey! It looks like you're using v3.0.0. The issue you're mentioning has been fixed already. Please update to the latest version (at the moment v3.2.0) and this issue will go away.

I'll close this for now, but feel free to re-open if you still encounter this with the new version
