### ISSUE TITLE
Docker on Mac & Synology

### ISSUE THREAD

**Issue by irfanarif-ia** [chartbrew/chartbrew#226]
I have been trying for hours trying to deploy this

Methods Use: 
- Your Docker Compose File
- New mysql Docker

Either i get CB Encryption Error or Error Connecting a database

Set up encryption key CB_ENCRYPTION_KEY_DEV
ConnectionRefusedError [SequelizeConnectionRefusedError]: connect ECONNREFUSED 192.168.65.254:3306
    at ConnectionManager.connect (/code/server/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:92:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/code/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /code/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/code/server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /code/server/node_modules/sequelize/lib/sequelize.js:305:26
    at async MySQLQueryInterface.tableExists (/code/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:102:17)
    at async SequelizeMeta.sync (/code/server/node_modules/sequelize/lib/model.js:939:21)
    at async SequelizeStorage.syncModel (/code/server/node_modules/umzug/lib/storage/sequelize.js:52:9)
    at async SequelizeStorage.executed (/code/server/node_modules/umzug/lib/storage/sequelize.js:69:9)
    at async Promise.all (index 1)
    at async Umzug._pending (/code/server/node_modules/umzug/lib/umzug.js:117:45)
    at async eligibleMigrations (/code/server/node_modules/umzug/lib/umzug.js:151:32)
    at async /code/server/node_modules/umzug/lib/umzug.js:159:33
    at async Umzug.runCommand (/code/server/node_modules/umzug/lib/umzug.js:125:20) {
  parent: Error: connect ECONNREFUSED 192.168.65.254:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.65.254',
    port: 3306,
    fatal: true
  },
  original: Error: connect ECONNREFUSED 192.168.65.254:3306
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.65.254',
    port: 3306,
    fatal: true
  }
}
Migrations failed, could not run the server app.
Set up encryption key CB_ENCRYPTION_KEY
✓ 3558 modules transformed.

**Comment by razvanilin** [comment]
Hey @irfanarif-ia you're getting this error because the app cannot connect to your database. I think your Docker container cannot access the database at `192.168.65.254:3306`

Maybe try setting up the host variable like this: `CB_DB_HOST=host.docker.internal`

**Comment by irfanarif-ia** [comment]
I don't know where i was getting that IP from, I change the Variable CB_DB_HOST=host.docker.internal to the "DB-Container Name" its working now thanks

My Settings
### Database connection parameters
CB_DB_NAME=chartbrew
CB_DB_USERNAME=chartbrew
CB_DB_PASSWORD=chartbrew
CB_DB_HOST=chartbrew-db-1
CB_DB_PORT=3306
CB_DB_CERT=
CB_DB_SSL=
CB_DB_SSL_KEY=
CB_DB_SSL_CERT=
