### ISSUE TITLE
Error on run server

### ISSUE THREAD

**Issue by francisconeto00** [chartbrew/chartbrew#240]
Hello, everyone, 
I would like to run Chartbrew locally, so I read the documentation. As a prerequisite I had to have a database, in which I created a mysql using XAMP.
I created the database with the name that was in the .env file - "chartbrewdev".
I ran npm run setup. I added a 64-char key in CB_ENCRYPTION_KEY_DEV.  When I ran "npm run start-dev" in the server folder, I got the error described below:

`MigrationError: Migration 20231209061034-add-layout-chart.js (up) failed: Original error: Unknown column 'Project.updateSchedule' in 'field list'
    at /Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/umzug/lib/umzug.js:169:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Umzug.runCommand (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/umzug/lib/umzug.js:125:20) {
  cause: Error
      at Query.run (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)
      at /Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/sequelize/lib/sequelize.js:315:28
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async MySQLQueryInterface.select (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
      at async Project.findAll (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/sequelize/lib/model.js:1140:21)
      at async Object.up (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/models/migrations/20231209061034-add-layout-chart.js:40:22)
      at async /Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/umzug/lib/umzug.js:166:21
      at async Umzug.runCommand (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/umzug/lib/umzug.js:125:20) {
    name: 'SequelizeDatabaseError',
    parent: Error: Unknown column 'Project.updateSchedule' in 'field list'
        at Packet.asError (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/packets/packet.js:738:17)
        at Query.execute (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/commands/command.js:29:26)
        at Connection.handlePacket (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/connection.js:481:34)
        at PacketParser.onPacket (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/connection.js:97:12)
        at PacketParser.executeStart (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/packet_parser.js:75:16)
        at Socket.<anonymous> (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/connection.js:104:25)
        at Socket.emit (node:events:511:28)
        at addChunk (node:internal/streams/readable:332:12)
        at readableAddChunk (node:internal/streams/readable:305:9)
        at Readable.push (node:internal/streams/readable:242:10)
        at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
      code: 'ER_BAD_FIELD_ERROR',
      errno: 1054,
      sqlState: '42S22',
      sqlMessage: "Unknown column 'Project.updateSchedule' in 'field list'",
      sql: 'SELECT `Project`.`id`, `Project`.`team_id`, `Project`.`name`, `Project`.`brewName`, `Project`.`dashboardTitle`, `Project`.`description`, `Project`.`backgroundColor`, `Project`.`titleColor`, `Project`.`headerCode`, `Project`.`footerCode`, `Project`.`logo`, `Project`.`logoLink`, `Project`.`public`, `Project`.`passwordProtected`, `Project`.`password`, `Project`.`timezone`, `Project`.`ghost`, `Project`.`updateSchedule`, `Project`.`lastUpdatedAt`, `Project`.`createdAt`, `Project`.`updatedAt`, `Charts`.`id` AS `Charts.id`, `Charts`.`chartSize` AS `Charts.chartSize`, `Charts`.`dashboardOrder` AS `Charts.dashboardOrder` FROM `Project` AS `Project` LEFT OUTER JOIN `Chart` AS `Charts` ON `Project`.`id` = `Charts`.`project_id`;',
      parameters: undefined
    },
    original: Error: Unknown column 'Project.updateSchedule' in 'field list'
        at Packet.asError (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/packets/packet.js:738:17)
        at Query.execute (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/commands/command.js:29:26)
        at Connection.handlePacket (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/connection.js:481:34)
        at PacketParser.onPacket (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/connection.js:97:12)
        at PacketParser.executeStart (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/packet_parser.js:75:16)
        at Socket.<anonymous> (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/connection.js:104:25)
        at Socket.emit (node:events:511:28)
        at addChunk (node:internal/streams/readable:332:12)
        at readableAddChunk (node:internal/streams/readable:305:9)
        at Readable.push (node:internal/streams/readable:242:10)
        at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
      code: 'ER_BAD_FIELD_ERROR',
      errno: 1054,
      sqlState: '42S22',
      sqlMessage: "Unknown column 'Project.updateSchedule' in 'field list'",
      sql: 'SELECT `Project`.`id`, `Project`.`team_id`, `Project`.`name`, `Project`.`brewName`, `Project`.`dashboardTitle`, `Project`.`description`, `Project`.`backgroundColor`, `Project`.`titleColor`, `Project`.`headerCode`, `Project`.`footerCode`, `Project`.`logo`, `Project`.`logoLink`, `Project`.`public`, `Project`.`passwordProtected`, `Project`.`password`, `Project`.`timezone`, `Project`.`ghost`, `Project`.`updateSchedule`, `Project`.`lastUpdatedAt`, `Project`.`createdAt`, `Project`.`updatedAt`, `Charts`.`id` AS `Charts.id`, `Charts`.`chartSize` AS `Charts.chartSize`, `Charts`.`dashboardOrder` AS `Charts.dashboardOrder` FROM `Project` AS `Project` LEFT OUTER JOIN `Chart` AS `Charts` ON `Project`.`id` = `Charts`.`project_id`;',
      parameters: undefined
    },
    sql: 'SELECT `Project`.`id`, `Project`.`team_id`, `Project`.`name`, `Project`.`brewName`, `Project`.`dashboardTitle`, `Project`.`description`, `Project`.`backgroundColor`, `Project`.`titleColor`, `Project`.`headerCode`, `Project`.`footerCode`, `Project`.`logo`, `Project`.`logoLink`, `Project`.`public`, `Project`.`passwordProtected`, `Project`.`password`, `Project`.`timezone`, `Project`.`ghost`, `Project`.`updateSchedule`, `Project`.`lastUpdatedAt`, `Project`.`createdAt`, `Project`.`updatedAt`, `Charts`.`id` AS `Charts.id`, `Charts`.`chartSize` AS `Charts.chartSize`, `Charts`.`dashboardOrder` AS `Charts.dashboardOrder` FROM `Project` AS `Project` LEFT OUTER JOIN `Chart` AS `Charts` ON `Project`.`id` = `Charts`.`project_id`;',
    parameters: {}
  },
  jse_cause: Error
      at Query.run (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)
      at /Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/sequelize/lib/sequelize.js:315:28
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async MySQLQueryInterface.select (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
      at async Project.findAll (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/sequelize/lib/model.js:1140:21)
      at async Object.up (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/models/migrations/20231209061034-add-layout-chart.js:40:22)
      at async /Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/umzug/lib/umzug.js:166:21
      at async Umzug.runCommand (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/umzug/lib/umzug.js:125:20) {
    name: 'SequelizeDatabaseError',
    parent: Error: Unknown column 'Project.updateSchedule' in 'field list'
        at Packet.asError (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/packets/packet.js:738:17)
        at Query.execute (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/commands/command.js:29:26)
        at Connection.handlePacket (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/connection.js:481:34)
        at PacketParser.onPacket (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/connection.js:97:12)
        at PacketParser.executeStart (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/packet_parser.js:75:16)
        at Socket.<anonymous> (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/connection.js:104:25)
        at Socket.emit (node:events:511:28)
        at addChunk (node:internal/streams/readable:332:12)
        at readableAddChunk (node:internal/streams/readable:305:9)
        at Readable.push (node:internal/streams/readable:242:10)
        at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
      code: 'ER_BAD_FIELD_ERROR',
      errno: 1054,
      sqlState: '42S22',
      sqlMessage: "Unknown column 'Project.updateSchedule' in 'field list'",
      sql: 'SELECT `Project`.`id`, `Project`.`team_id`, `Project`.`name`, `Project`.`brewName`, `Project`.`dashboardTitle`, `Project`.`description`, `Project`.`backgroundColor`, `Project`.`titleColor`, `Project`.`headerCode`, `Project`.`footerCode`, `Project`.`logo`, `Project`.`logoLink`, `Project`.`public`, `Project`.`passwordProtected`, `Project`.`password`, `Project`.`timezone`, `Project`.`ghost`, `Project`.`updateSchedule`, `Project`.`lastUpdatedAt`, `Project`.`createdAt`, `Project`.`updatedAt`, `Charts`.`id` AS `Charts.id`, `Charts`.`chartSize` AS `Charts.chartSize`, `Charts`.`dashboardOrder` AS `Charts.dashboardOrder` FROM `Project` AS `Project` LEFT OUTER JOIN `Chart` AS `Charts` ON `Project`.`id` = `Charts`.`project_id`;',
      parameters: undefined
    },
    original: Error: Unknown column 'Project.updateSchedule' in 'field list'
        at Packet.asError (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/packets/packet.js:738:17)
        at Query.execute (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/commands/command.js:29:26)
        at Connection.handlePacket (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/connection.js:481:34)
        at PacketParser.onPacket (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/connection.js:97:12)
        at PacketParser.executeStart (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/packet_parser.js:75:16)
        at Socket.<anonymous> (/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/node_modules/mysql2/lib/connection.js:104:25)
        at Socket.emit (node:events:511:28)
        at addChunk (node:internal/streams/readable:332:12)
        at readableAddChunk (node:internal/streams/readable:305:9)
        at Readable.push (node:internal/streams/readable:242:10)
        at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
      code: 'ER_BAD_FIELD_ERROR',
      errno: 1054,
      sqlState: '42S22',
      sqlMessage: "Unknown column 'Project.updateSchedule' in 'field list'",
      sql: 'SELECT `Project`.`id`, `Project`.`team_id`, `Project`.`name`, `Project`.`brewName`, `Project`.`dashboardTitle`, `Project`.`description`, `Project`.`backgroundColor`, `Project`.`titleColor`, `Project`.`headerCode`, `Project`.`footerCode`, `Project`.`logo`, `Project`.`logoLink`, `Project`.`public`, `Project`.`passwordProtected`, `Project`.`password`, `Project`.`timezone`, `Project`.`ghost`, `Project`.`updateSchedule`, `Project`.`lastUpdatedAt`, `Project`.`createdAt`, `Project`.`updatedAt`, `Charts`.`id` AS `Charts.id`, `Charts`.`chartSize` AS `Charts.chartSize`, `Charts`.`dashboardOrder` AS `Charts.dashboardOrder` FROM `Project` AS `Project` LEFT OUTER JOIN `Chart` AS `Charts` ON `Project`.`id` = `Charts`.`project_id`;',
      parameters: undefined
    },
    sql: 'SELECT `Project`.`id`, `Project`.`team_id`, `Project`.`name`, `Project`.`brewName`, `Project`.`dashboardTitle`, `Project`.`description`, `Project`.`backgroundColor`, `Project`.`titleColor`, `Project`.`headerCode`, `Project`.`footerCode`, `Project`.`logo`, `Project`.`logoLink`, `Project`.`public`, `Project`.`passwordProtected`, `Project`.`password`, `Project`.`timezone`, `Project`.`ghost`, `Project`.`updateSchedule`, `Project`.`lastUpdatedAt`, `Project`.`createdAt`, `Project`.`updatedAt`, `Charts`.`id` AS `Charts.id`, `Charts`.`chartSize` AS `Charts.chartSize`, `Charts`.`dashboardOrder` AS `Charts.dashboardOrder` FROM `Project` AS `Project` LEFT OUTER JOIN `Chart` AS `Charts` ON `Project`.`id` = `Charts`.`project_id`;',
    parameters: {}
  },
  migration: {
    direction: 'up',
    name: '20231209061034-add-layout-chart.js',
    path: '/Users/francisconeto/Desktop/Chartbrew/chartbrew/server/models/migrations/20231209061034-add-layout-chart.js',
    context: MySQLQueryInterface {
      sequelize: [Sequelize],
      queryGenerator: [MySQLQueryGenerator]
    }
  }
}
Migrations failed, could not run the server app.`

**Comment by razvanilin** [comment]
Fixed in the latest on `master`
