### ISSUE TITLE
render deploy failed

### ISSUE THREAD

**Issue by nileblack** [chartbrew/chartbrew#264]
```
> server@v3.10.0 postinstall
> npx playwright install && npx playwright install-deps
.....

Webkit 18.0 (playwright build v2083) downloaded to /opt/render/.cache/ms-playwright/webkit-2083
Playwright Host validation warning: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libgstgl-1.0.so.0                                ║
║     libgstcodecparsers-1.0.so.0                      ║
║     libenchant-2.so.2                                ║
║     libsecret-1.so.0                                 ║
║     libmanette-0.2.so.0                              ║
║     libGLESv2.so.2                                   ║
╚══════════════════════════════════════════════════════╝
    at validateDependenciesLinux (/opt/render/project/src/server/node_modules/playwright-core/lib/server/registry/dependencies.js:216:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Registry._validateHostRequirements (/opt/render/project/src/server/node_modules/playwright-core/lib/server/registry/index.js:707:43)
    at async Registry._validateHostRequirementsForExecutableIfNeeded (/opt/render/project/src/server/node_modules/playwright-core/lib/server/registry/index.js:805:7)
    at async Registry.validateHostRequirementsForExecutablesIfNeeded (/opt/render/project/src/server/node_modules/playwright-core/lib/server/registry/index.js:794:43)
    at async t.<anonymous> (/opt/render/project/src/server/node_modules/playwright-core/lib/cli/program.js:119:7)
Installing dependencies...
Switching to root user to install dependencies...
Password: su: Authentication failure
Failed to install browser dependencies
Error: Installation process exited with code: 1
npm error code 1
npm error path /opt/render/project/src/server
npm error command failed
npm error command sh -c npx playwright install && npx playwright install-deps
```

**Comment by razvanilin** [comment]
It looks like playwright cannot install OS-level dependencies on Render. I'll have to play around after the Holidays to see if I can find an alternative way to set it up.

For now, if you're familiar with Docker, you can deploy Chartbrew on Render with Docker and install Playwright separately like in this example: https://community.render.com/t/how-to-deploy-nodejs-playwright-installing-deps-for-chromium/4106/2 

You can then modify the `Dockerfile` for Chartbrew to look like this (notice the addition of the playwright dependency on the 2nd line):

```
FROM node:20-slim
FROM mcr.microsoft.com/playwright:v1.49.1-noble

WORKDIR /code
COPY . .

RUN apt-get update && apt-get install -y gnupg && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138 F0235973A478C4D3 || \
    true && apt-get update

RUN cd client && npm install && cd ../server && npm install && npx playwright install-deps && npx playwright install
RUN npm run prepareSettings

RUN echo -e "\nBuilding the UI. This might take a couple of minutes...\n"
RUN cd client && npm run build

EXPOSE 4018
EXPOSE 4019

ENTRYPOINT ["./entrypoint.sh"]
```
