### ISSUE TITLE
ERROR: Validation error when first migration

### ISSUE THREAD

**Issue by keremkurtulus** [chartbrew/chartbrew#97]
When first migration I am getting this 
```bash
...
== 20200409043937-connections-on-datasets: migrating =======

ERROR: Validation error
```
I am on the dev mode and using MAMP 6.3 for MySQL on macOS

Also, I think the migration command should be on the getting started page in docs.

Thanks.

**Comment by razvanilin** [comment]
Hey @keremkurtulus, sorry for the delay in getting back to this!

Did you run the migration manually? There should be running automatically now.

Have you started the app and you get any errors?

**Comment by may-qmh** [comment]
Hi, I faced this issue as well when running migration manually. 

Auto migration does not work for me, running the commands recommended in the docs to run the project in Development:
```sh
# frontend
cd client/
npm run start

# backend
cd server/
npm run start-dev
```

resulted in db errors:
```
> server@v1.16.1 start-dev
> set NODE_ENV=development && nodemon index

[nodemon] 2.0.14
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index index.js`
Running server on port 3210
DatabaseError [SequelizeDatabaseError]: Unknown column 'Team.showBranding' in 'field list'
    at Query.formatError (/chartbrew/server/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)
    at Query.run (/chartbrew/server/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'SequelizeDatabaseError',
  parent: Error: Unknown column 'Team.showBranding' in 'field list'
      at Packet.asError (/chartbrew/server/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/chartbrew/server/node_modules/mysql2/lib/commands/command.js:29:26)
      at Connection.handlePacket (/chartbrew/server/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/chartbrew/server/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/chartbrew/server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/chartbrew/server/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (events.js:210:5)
      at addChunk (_stream_readable.js:308:12)
      at readableAddChunk (_stream_readable.js:289:11)
      at Socket.Readable.push (_stream_readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'Team.showBranding' in 'field list'",
    sql: 'SELECT `Team`.`id`, `Team`.`name`, `Team`.`showBranding`, `Team`.`createdAt`, `Team`.`updatedAt`, `Projects`.`id` AS `Projects.id`, `Projects`.`team_id` AS `Projects.team_id`, `Projects`.`name` AS `Projects.name`, `Projects`.`brewName` AS `Projects.brewName`, `Projects`.`dashboardTitle` AS `Projects.dashboardTitle`, `Projects`.`description` AS `Projects.description`, `Projects`.`backgroundColor` AS `Projects.backgroundColor`, `Projects`.`titleColor` AS `Projects.titleColor`, `Projects`.`headerCode` AS `Projects.headerCode`, `Projects`.`footerCode` AS `Projects.footerCode`, `Projects`.`logo` AS `Projects.logo`, `Projects`.`logoLink` AS `Projects.logoLink`, `Projects`.`createdAt` AS `Projects.createdAt`, `Projects`.`updatedAt` AS `Projects.updatedAt` FROM `Team` AS `Team` LEFT OUTER JOIN `Project` AS `Projects` ON `Team`.`id` = `Projects`.`team_id`;',
    parameters: undefined
  },
  original: Error: Unknown column 'Team.showBranding' in 'field list'
      at Packet.asError (/chartbrew/server/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/chartbrew/server/node_modules/mysql2/lib/commands/command.js:29:26)
      at Connection.handlePacket (/chartbrew/server/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/chartbrew/server/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/chartbrew/server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/chartbrew/server/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (events.js:210:5)
      at addChunk (_stream_readable.js:308:12)
      at readableAddChunk (_stream_readable.js:289:11)
      at Socket.Readable.push (_stream_readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'Team.showBranding' in 'field list'",
    sql: 'SELECT `Team`.`id`, `Team`.`name`, `Team`.`showBranding`, `Team`.`createdAt`, `Team`.`updatedAt`, `Projects`.`id` AS `Projects.id`, `Projects`.`team_id` AS `Projects.team_id`, `Projects`.`name` AS `Projects.name`, `Projects`.`brewName` AS `Projects.brewName`, `Projects`.`dashboardTitle` AS `Projects.dashboardTitle`, `Projects`.`description` AS `Projects.description`, `Projects`.`backgroundColor` AS `Projects.backgroundColor`, `Projects`.`titleColor` AS `Projects.titleColor`, `Projects`.`headerCode` AS `Projects.headerCode`, `Projects`.`footerCode` AS `Projects.footerCode`, `Projects`.`logo` AS `Projects.logo`, `Projects`.`logoLink` AS `Projects.logoLink`, `Projects`.`createdAt` AS `Projects.createdAt`, `Projects`.`updatedAt` AS `Projects.updatedAt` FROM `Team` AS `Team` LEFT OUTER JOIN `Project` AS `Projects` ON `Team`.`id` = `Projects`.`team_id`;',
    parameters: undefined
  },
  sql: 'SELECT `Team`.`id`, `Team`.`name`, `Team`.`showBranding`, `Team`.`createdAt`, `Team`.`updatedAt`, `Projects`.`id` AS `Projects.id`, `Projects`.`team_id` AS `Projects.team_id`, `Projects`.`name` AS `Projects.name`, `Projects`.`brewName` AS `Projects.brewName`, `Projects`.`dashboardTitle` AS `Projects.dashboardTitle`, `Projects`.`description` AS `Projects.description`, `Projects`.`backgroundColor` AS `Projects.backgroundColor`, `Projects`.`titleColor` AS `Projects.titleColor`, `Projects`.`headerCode` AS `Projects.headerCode`, `Projects`.`footerCode` AS `Projects.footerCode`, `Projects`.`logo` AS `Projects.logo`, `Projects`.`logoLink` AS `Projects.logoLink`, `Projects`.`createdAt` AS `Projects.createdAt`, `Projects`.`updatedAt` AS `Projects.updatedAt` FROM `Team` AS `Team` LEFT OUTER JOIN `Project` AS `Projects` ON `Team`.`id` = `Projects`.`team_id`;',
  parameters: undefined
}
OPTIONS /user 204 3.806 ms - 0
(node:27810) [DEP0106] DeprecationWarning: crypto.createCipher is deprecated.
POST /user 400 61.705 ms - 2
```

When I ran migration with `npm run db:migrate` on a clean project, I get validation error. Re-running it again (a few times) overcomes the validation error and would result in the same db error as above. 

Due to my lack of knowledge I manually resolved the column issues on my local db by adding/dropping the columns. It does seem like there are some order/dependency issues with the migration files. For columns that I have added/dropped it would clear one migration step and cause an issue in a later one where I would then have to drop/add back the columns.

**Comment by razvanilin** [comment]
Hey @may-qmh thanks for reporting this! Things have changed since this issue was first reported so I think the problem now is the order in which the migration actions are running. I'll look into this and fix the migrations 👍

Have you cloned the repository or installed with `create-chartbrew-app`?

**Comment by razvanilin** [comment]
@may-qmh I managed to replicate the issue in my test environment and fixed it on `master`. You can pull the latest changes or wait until I release the new version to use `create-chartbrew-app` if that's the method you prefer. Before running the server app again, it's better if you drop the database and re-create it so the migrations start from the beginning.

Again, thanks for reporting as this was an important fix for new chartbrew installations
